### PR TITLE
Fixed typo in variable

### PR DESCRIPTION
**Pull request by jadamec**

### CODE REVIEW

**Review by antonkomarev — APPROVED** [review]

**Comment by antonkomarev** [comment]
Thank you for the fix @jadamec

**Comment by antonkomarev** [comment]
[Laravel Ban v4.6.1](https://github.com/cybercog/laravel-ban/releases/tag/4.6.1) has been released!

**Comment by antonkomarev** [comment]
[Contributors list](https://github.com/cybercog/laravel-ban#contributors] has been updated too.

**Comment by jadamec** [comment]
That was so fast! 👍  Thank you.

**Pull request merged**
