### PR TITLE
Allow Laravel 6

### PR DESCRIPTION
**Pull request by JayBizzle**

### CODE REVIEW

**Comment by antonkomarev** [comment]
Thank you for the contribution @JayBizzle!

I will merge it as soon as v6 will be published to be able to test everything on stable version.

**Comment by antonkomarev** [comment]
@JayBizzle I've tested Laravel 6 and your changes are not enough. Here is a complete list of required changes which I've made in another package: https://github.com/cybercog/laravel-love/pull/113/files

**Comment by JayBizzle** [comment]
Thanks @antonkomarev, those changes should now be ready 👍

**Comment by antonkomarev** [comment]
Test is failing.

I've fixed this issue with `--realpath` in `tests/TestCase.php` file when upgraded old version of [Laravel Love](https://github.com/cybercog/laravel-love/pull/114/files#diff-d4c8c6dc8769324fc27cfdac19f05caf).

**Comment by antonkomarev** [comment]
Thank you for the contribution @JayBizzle. I've merged similar PR which has all the required fixes: #48

**Comment by JayBizzle** [comment]
No worries 👍

**Pull request closed without merging**
