### PR TITLE
Added Inertia Fix

### PR DESCRIPTION
**Pull request by Im-Fran**
Implemented a fix for the inertia response code. (Issue #68 )

### CODE REVIEW

**Comment by antonkomarev** [comment]
@Im-Fran does Inertia add any headers? We might check them to understand that this is Inertia request and apply this hack without adding any config.
There are [issues with code style](https://github.styleci.io/analyses/Yjw77y)

**Comment by antonkomarev** [comment]
It looks like Inertia adds `X-Inertia: true` header to each request. Let's use it then!

**Comment by antonkomarev** [comment]
Additionally this will cover the case when some of the endpoints are requested with Inertia and others not.

**Comment by Im-Fran** [comment]
I'll add the check `$request->get('X-Inertia')`, because older versions of inertia automatically adds the 303 redirect, but newer versions not, so this is why I used the configuration file for the check.

**Comment by antonkomarev** [comment]
Why do we need config value? Header should be enough

**Comment by Im-Fran** [comment]
> Why do we need config value? Header should be enough

Like I said, some older installations of Inertia automatically change the response code, or if some users want to just disable the feature

**Comment by antonkomarev** [comment]
Why should they disable it if Inertia requires this response code?

**Comment by Im-Fran** [comment]
> Why should they disable it if Inertia requires this response code?

I was just thinking that X user would want to disable the feature, but sure, I'll close this pr and make another one to fix the issue, is not needed to have a lot of commits :laughing:

**Comment by antonkomarev** [comment]
A lot of commits not a problem, I'm always doing squash & merge ;) But do as you are comfortable.

**Pull request closed without merging**
